# Generated by Django 5.1.1 on 2024-11-27 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agency_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(max_length=255)),
                ('stop_lat', models.FloatField()),
                ('stop_lon', models.FloatField()),
                ('stop_code', models.CharField(blank=True, max_length=255, null=True)),
                ('zone_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=50)),
                ('long_name', models.CharField(max_length=255)),
                ('route_type', models.IntegerField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transit.agency')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('service_id', models.CharField(max_length=255)),
                ('trip_headsign', models.CharField(blank=True, max_length=255, null=True)),
                ('direction_id', models.IntegerField()),
                ('block_id', models.CharField(blank=True, max_length=255, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transit.route')),
            ],
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('stop_sequence', models.IntegerField()),
                ('stop_headsign', models.CharField(blank=True, max_length=255, null=True)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transit.stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transit.trip')),
            ],
            options={
                'ordering': ['trip', 'stop_sequence'],
            },
        ),
    ]
