# Generated by Django 5.1.3 on 2024-12-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='stoptime',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='stoptime',
            name='departure_time',
            field=models.TimeField(),
        ),
    ]
