# Generated by Django 5.1.1 on 2024-12-09 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agency_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('agency_name', models.CharField(default='Default Agency', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('stop_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('route_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('route_long_name', models.CharField(max_length=100)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideshare.agency')),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('trip_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideshare.routes')),
            ],
        ),
        migrations.CreateModel(
            name='StopTimes',
            fields=[
                ('stop_time_id', models.AutoField(primary_key=True, serialize=False)),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideshare.stops')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideshare.trips')),
            ],
        ),
    ]
