# Generated by Django 5.1.1 on 2024-12-09 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='routes',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='route',
        ),
        migrations.RemoveField(
            model_name='stoptimes',
            name='stop',
        ),
        migrations.RemoveField(
            model_name='stoptimes',
            name='trip',
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideshare.stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rideshare.trip')),
            ],
        ),
        migrations.DeleteModel(
            name='Agency',
        ),
        migrations.DeleteModel(
            name='Routes',
        ),
        migrations.DeleteModel(
            name='Stops',
        ),
        migrations.DeleteModel(
            name='StopTimes',
        ),
        migrations.DeleteModel(
            name='Trips',
        ),
    ]
